package model;
// Generated 10/04/2013 09:44:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private int idevento;
     private Usuario usuario;
     private String descricao;
     private Date data;
     private String importancia;
     private String hora;
     private String local;
     private Double valor;
     private String agencia;
     private String conta;
     private String banco;

    public Deposito() {
    }

	
    public Deposito(int idevento) {
        this.idevento = idevento;
    }
    public Deposito(int idevento, Usuario usuario, String descricao, Date data, String importancia, String hora, String local, Double valor, String agencia, String conta, String banco) {
       this.idevento = idevento;
       this.usuario = usuario;
       this.descricao = descricao;
       this.data = data;
       this.importancia = importancia;
       this.hora = hora;
       this.local = local;
       this.valor = valor;
       this.agencia = agencia;
       this.conta = conta;
       this.banco = banco;
    }
   
    public int getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(int idevento) {
        this.idevento = idevento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getImportancia() {
        return this.importancia;
    }
    
    public void setImportancia(String importancia) {
        this.importancia = importancia;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getConta() {
        return this.conta;
    }
    
    public void setConta(String conta) {
        this.conta = conta;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }




}


