package model;
// Generated 10/04/2013 09:44:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String username;
     private String senha;
     private Set trabalhos = new HashSet(0);
     private Set reuniaos = new HashSet(0);
     private Set contas = new HashSet(0);
     private Set outroagendas = new HashSet(0);
     private Set outrofinanceiros = new HashSet(0);
     private Set seminarios = new HashSet(0);
     private Set outroestudantes = new HashSet(0);
     private Set depositos = new HashSet(0);
     private Set aniversarios = new HashSet(0);
     private Set provas = new HashSet(0);
     private Set compras = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String username) {
        this.username = username;
    }
    public Usuario(String username, String senha, Set trabalhos, Set reuniaos, Set contas, Set outroagendas, Set outrofinanceiros, Set seminarios, Set outroestudantes, Set depositos, Set aniversarios, Set provas, Set compras) {
       this.username = username;
       this.senha = senha;
       this.trabalhos = trabalhos;
       this.reuniaos = reuniaos;
       this.contas = contas;
       this.outroagendas = outroagendas;
       this.outrofinanceiros = outrofinanceiros;
       this.seminarios = seminarios;
       this.outroestudantes = outroestudantes;
       this.depositos = depositos;
       this.aniversarios = aniversarios;
       this.provas = provas;
       this.compras = compras;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getTrabalhos() {
        return this.trabalhos;
    }
    
    public void setTrabalhos(Set trabalhos) {
        this.trabalhos = trabalhos;
    }
    public Set getReuniaos() {
        return this.reuniaos;
    }
    
    public void setReuniaos(Set reuniaos) {
        this.reuniaos = reuniaos;
    }
    public Set getContas() {
        return this.contas;
    }
    
    public void setContas(Set contas) {
        this.contas = contas;
    }
    public Set getOutroagendas() {
        return this.outroagendas;
    }
    
    public void setOutroagendas(Set outroagendas) {
        this.outroagendas = outroagendas;
    }
    public Set getOutrofinanceiros() {
        return this.outrofinanceiros;
    }
    
    public void setOutrofinanceiros(Set outrofinanceiros) {
        this.outrofinanceiros = outrofinanceiros;
    }
    public Set getSeminarios() {
        return this.seminarios;
    }
    
    public void setSeminarios(Set seminarios) {
        this.seminarios = seminarios;
    }
    public Set getOutroestudantes() {
        return this.outroestudantes;
    }
    
    public void setOutroestudantes(Set outroestudantes) {
        this.outroestudantes = outroestudantes;
    }
    public Set getDepositos() {
        return this.depositos;
    }
    
    public void setDepositos(Set depositos) {
        this.depositos = depositos;
    }
    public Set getAniversarios() {
        return this.aniversarios;
    }
    
    public void setAniversarios(Set aniversarios) {
        this.aniversarios = aniversarios;
    }
    public Set getProvas() {
        return this.provas;
    }
    
    public void setProvas(Set provas) {
        this.provas = provas;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


